---

# common
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  roles:
    - common

# web
- hosts: web
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - web

# lb
- hosts: lb
  become: yes
  become_user: root
  become_method: sudo  

  roles:
    - lb
